app:
    name: HelloApp
    version: 1.0.0
    author:
        name: Tester
        email: tester@domain.com
server:
    port: 8080
spring:
    profiles:
        active: local
    application:
        name: demo
    # DATABASE(POSTGRESQL)
    datasource:
        url: jdbc:postgresql://localhost:5432/dslab
        username: system
        password: pass
        driver-class-name: org.postgresql.Driver
    # JPA
    jpa:
        hibernate:
            ddl-auto: validate  # 또는 create, create-drop, update
        show-sql: true
        properties:
            hibernate:
                format_sql: true